### ISSUE TITLE
Fails to load solcjs

### ISSUE THREAD

**Issue by juztin** [4c0n/remix-ide-docker#4]
Following the instructions from: https://hub.docker.com/r/4c0n/remix-ide

 1. From within my project, I run:  
     ```
     docker run \
         -it  \
         -publish 8080:8080 \
         -publish 65520:65520 \
         -volume "$(pwd)/contracts/":/app \
         4c0n/remix-ide
      ```
 2. Open browser and navigate to `http://localhost:8545`  
     from the dev console I get:  
     _(same result in both Firefox/Chrome)_   
     ```
     Loading https://solc-bin.ethereum.org/bin/soljson-v0.5.6+commit.b259423e.js with worker app.js:190693:5
     Assertion failed: Cannot call unknown function version, make sure it is exported soljson-v0.5.6+commit.b259423e.js:28:12825
     Assertion failed: Cannot call unknown function version, make sure it is exported soljson-v0.5.6+commit.b259423e.js:28:12835
     uncaught exception: abort("Assertion failed: Cannot call unknown function version, make sure it is exported"). Build with -s ASSERTIONS=1 for more info.
     ```
     Comparing this to `https://remix.ethereum.org`, I get the same logs, minus the assertions.

I've tried the `current` tagged image, as well as `0.7.2`.

**Comment by juztin** [comment]
Hmm, just poking around I noticed that if I select `0.1.1` or `0.1.2`, `0.3.2`, `0.3.4`, they work.  
Selecting `0.1.3`, `0.1.4`, `0.1.5`, `0.3.6`, `0.4.7`, `0.4.10`, `0.4.22`:  
```
TypeError: asm.js type error: 'byteLength' is not a standard constant or typed array name soljson-v0.1.5+commit.23865e3.js:3:373
too much recursion[Learn More] c8f7af8d-08b3-6c42-9820-57ffee7e3a0d:7682:9
NetworkError: A network error occurred.
```

Selecting `0.5.5`, `0.5.6`:  
```
Assertion failed: Cannot call unknown function version, make sure it is exported soljson-v0.5.6+commit.b259423e.js:28:12825
Assertion failed: Cannot call unknown function version, make sure it is exported soljson-v0.5.6+commit.b259423e.js:28:12835
uncaught exception: abort("Assertion failed: Cannot call unknown function version, make sure it is exported"). Build with -s ASSERTIONS=1 for more info.
```  

Selecting `0.5.1`, `0.5.2`:
```
uncaught exception: abort("NO_DYNAMIC_EXECUTION=1 was set, cannot eval") at jsStackTrace@https://solc-bin.ethereum.org/bin/soljson-v0.5.2+commit.1df8f40c.js:1:16626
stackTrace@https://solc-bin.ethereum.org/bin/soljson-v0.5.2+commit.1df8f40c.js:1:16797
abort@https://solc-bin.ethereum.org/bin/soljson-v0.5.2+commit.1df8f40c.js:20:12696
getCFunc@https://solc-bin.ethereum.org/bin/soljson-v0.5.2+commit.1df8f40c.js:1:8136
ccallFunc@https://solc-bin.ethereum.org/bin/soljson-v0.5.2+commit.1df8f40c.js:1:8864
cwrap/<@https://solc-bin.ethereum.org/bin/soljson-v0.5.2+commit.1df8f40c.js:1:9400
[1241]</module.exports/<@blob:http://jack-rabbit.local:8080/4ac83800-5507-244d-9f42-8bccd1e5b1aa:7699:17

If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```

The above were all from FireFox, running with Chrome I get a few more successes _(`0.4.6` works in Chrome)_

_(all the above versions are releases commits, not nightly)_

**Comment by 4c0n** [comment]
@juztin Thanks for your report. Do you feel this related to the Docker setup somehow? Or would installing and running this through NPM give the same result?
Basically that is all that the image does, so it might be worth checking out. I don't have a lot of time to try/debug any of this at the moment.

**Comment by juztin** [comment]
Yeah, I was initially thinking the same, but like you, time is sparse at the moment.

I'll try and find some time to dink around with a native/local NPM install and see if I can replicate _(maybe some goofy package/version/whatever)_

I'll post any updates.
Thanks =)

**Comment by 4c0n** [comment]
Awesome, thank you!

Op di 26 mrt. 2019 20:15 schreef juztin <notifications@github.com>:

**Comment by juztin** [comment]
Hey @4c0n 

I've got it all working, although I didn't pin-point the issue, just updated versions and re-built.
I've got some updates to `Dockerfile` and `entrypoint.sh` that will make it easier in the future to update versions of dependencies. 

I can make a PR if you'd like _(which would also resolve the stale #2)_?

**Comment by 4c0n** [comment]
Hi @juztin that would be awesome. Thank you very much. Great display of community spirit!

**Comment by juztin** [comment]
Created #5 

A rebuild, and push of the Docker image will resolve this and #2   
_(just puts all the versions into variables at the top of `Dockerfile` to make it easier to update the build)_

One other thing that'd be nice would be to create an Autobuild in Dockerhub, just off of a Git tag on the repo. This way you could update just those variables in the `Dockerfile` and tag that commit as the Remix-IDE version. Docker would pick up that push, and build/push the new image.

Thanks!  
_(hopefully it looks good)_ =)

**Comment by 4c0n** [comment]
Thanks I'll review and merge it soon. There's already an autobuild that
pushes to the Docker hub based on tags right now :)

Op ma 1 apr. 2019 17:59 schreef juztin <notifications@github.com>:

**Comment by juztin** [comment]
Doh! I totally missed seeing the tags =)
